### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by DunkleMelone** [roman015/InfiniteCraftAutomation#1]
Hi I'm stupid and want to know how to use it c:

**Comment by DunkleMelone** [comment]
Figured it out im just stupid (as said xD
)

**Comment by roman015** [comment]
Don't sell yourself short @DunkleMelone, sometimes the best way to solve a problem no matter how tough or trivial... is to just take some time off from it and then come back with a clear head. Or just ask and hope for a response.

Also - I added the minified version of the JavaScript code if anyone just wants to copy and paste it quickly into the address bar.
