### ISSUE TITLE
Can't Get It To Work

### ISSUE THREAD

**Issue by Polar0fficial** [roman015/InfiniteCraftAutomation#3]
I pasted the JavaScript code into the console, and I got this error, "Uncaught SyntaxError: Lexical declaration cannot appear in a single-statement context"

**Comment by roman015** [comment]
I haven't made any recent changes, but it looks like it's still working for me with only one catch now - I need to reduce the browser window size to be small enough for the mobile interface to appear first. If the website appears in desktop mode, nothing happens anymore.

![howtoGif](https://github.com/roman015/InfiniteCraftAutomation/assets/10479712/51a2e37c-253e-4a5d-b38a-a98495e3fd52)


I'll need more info to figure out what's going on in this issue:

1. Are you using this in full screen or are you shrinking the window to be small enough for the mobile interface to appear?
2. Which browser are you using?
3. Are you using the minified code in the address bar or the full code in the DevTools window?
