### ISSUE TITLE
I can't get it to run

### ISSUE THREAD

**Issue by KYLEGULLIT** [roman015/InfiniteCraftAutomation#4]
I have done what you said, and it doesn't work I first type in JavaScript: and then copy paste the minified JavaScript code but it doesn't work do you know how I can get this to work.

**Comment by roman015** [comment]
Previously the website had a different interface for mobile devices (and tiny desktop windows) that didn't require drag and dropping the elements onto the playing field. This was the UI that the JavaScript code was based on. 

The website is updated and the old UI is no longer there - I'll need to rework a significant part of the code to get around this.
